name: Workflow Validation

on:
  pull_request:
    paths:
      - '.github/**.yml'

concurrency:
  group: workflow-validation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-actions:
    name: Lint Actions
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      # Neither inline shellcheck disable, nor actionlint_flags
      # disable a rule, disabling using this shell variable.
      - run: export SHELLCHECK_OPTS="-e SC2129"
      - uses: reviewdog/action-actionlint@v1
